services:
  dev-server:
    image: node
    volumes:
      - ../frontend:/frontend
    working_dir: /frontend
    command: npm run dev
    ports:
      - 5173:5173

  api:
    image: node
    volumes:
      - ./api:/api
      - /home/sa/code/other-peoples-code:/repos
    working_dir: /api
    #env_file: ./api/.env
    command: node api.js